### ISSUE TITLE
It's an interesting plugin.

### ISSUE THREAD

**Issue by OPEN1004MIND** [OlegWock/obsidian-emera#1]
Hi,
It would be helpful for someone who knows JS well.
But I am a java beginner.
I would appreciate it if you could share an example of the inline and callout of the rainbow effect applied in the sample.
For a beginner who doesn't know coding, setting up index.js is not easy.
Thank you reading.

**Comment by OlegWock** [comment]
Hello. Here is source for components used in demo.

styles.css

```css
.InlineCallout {
    padding: 2px 5px;
    position: relative;
    z-index: 1;
}

.InlineCallout:before {
    content: " ";
    position: absolute;
    inset: 0;
    opacity: .4; 
    z-index: -1;
    border-radius: 8px;
    background: linear-gradient(in hsl longer hue 45deg, red 0 0);
}

.Alert {
    padding: 0.75rem 1.5rem;
    border-radius: 0.75rem;
    border: 4px solid transparent;
    border-image: linear-gradient(to bottom right, #b827fc 0%, #2c90fc 25%, #b8fd33 50%, #fec837 75%, #fd1892 100%);
    border-image-slice: 1;
}
```

components.jsx
```jsx
import { Markdown } from 'emera';

export const Alert = ({ children }) => {
    return (<div className="Alert">{typeof children === 'string' ? <Markdown>{children}</Markdown> : children}</div>)
};

export const InlineCallout = ({ children }) => {
    return (<span className="InlineCallout">{children}</span>)
}
```

index.js
```js
export * from './components';
```

Usage like this 

````markdown
```emmd:Alert
Text inside rainbow alert
```
````

````markdown
Some text with `emera:<InlineCallout>inline callout</InlineCallout>`
````
